spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: admin
    username: loja_qa
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
