spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: loja_qa
    username: admin
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
