spring:
  datasource:
    url: jdbc:oracle:thin:@svuxddb5:1521:dtbs
    password: asap
    username: asap
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
