server:
  port: 8082
  
spring:
  application:
    name: 'loja'
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8089/user
      
hystrix:  shareSecurityContext: true